name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Node
      uses: actions/setup-node@v2.1.4
        
    - name: Clone Organice
      run: git clone https://github.com/200ok-ch/organice
    
    - name: Build Organice
      run: cd organice && yarn build && yarn cache clean && rm -rf node_modules && rm -rf .git

    - name: Build
      run: go build -v ./...

