name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12

    - name: Install gover and Go 1.16beta1
      run: go get suah.dev/gover && gover download 1.16beta1
        
    - name: Clone Organice
      run: git clone https://github.com/200ok-ch/organice organice_repo
    
    - name: Build Organice
      run: cd organice_repo && yarn build && yarn cache clean && rm -rf node_modules && rm -rf .git

    - name: Copy Organice into gavin
      run: cp -r organice_repo/build organice

    - name: Build
      run: gover 1.16beta1 build -v ./...

